window.TEACHER_NOTES={
"Cap. 0":{it:"Buongiorno. Non e una lezione di catalogo. Un oggetto tessile diventa moda solo quando un sistema lo nomina: rivista, sfilata, buyer, editor.",en:"A garment becomes fashion when a system names it."},
"Cap. 1":{it:"Presentazioni. Tu 60 secondi. Loro: nome, citta, rivista, 45 secondi in inglese.",en:"Intros. Name, city, magazine. 45 seconds in English."},
"Cap. 2":{it:"Tre assi: ruolo, ricerca, composizione. Barthes, Mower, Kawamura.",en:"Three axes. Barthes, Mower, Kawamura."},
"Cap. 3":{it:"Barthes 1967. Capo reale, capo-immagine, capo scritto. Non e l oggetto, e il nome.",en:"Barthes 1967. Real, image, written. It is the name."},
"Cap. 4":{it:"Kawamura. Clothing materiale. Fashion credenza. Lo stylist e un operatore del sistema.",en:"Kawamura. Clothing is material. Fashion is belief."},
"Cap. 5":{it:"Sei fasi. Lo stylist e visibile in comunicazione. Deve leggere la produzione.",en:"Six stages. Communication plus production."},
"Cap. 6":{it:"Mower: interpreter, not designer. Editor, fotografo, buyer, CD, PR.",en:"Mower: interpreter, not designer."},
"Cap. 7":{it:"Editorial, advertising, celebrity, e-commerce, runway.",en:"Five fields."},
"Cap. 8":{it:"Cinque domande sulla copertina. Chi, rivista, stagione, tesi, credito.",en:"Five questions on the cover."},
"Cap. 9":{it:"Fad non e trend. Origine, filtro, cassa.",en:"A fad is not a trend."},
"Cap. 10":{it:"NY Londra Milano Parigi. Lo show costruisce mito.",en:"Four cities. The show builds myth."},
"Cap. 11":{it:"Vittima copia. Interprete sceglie.",en:"Victim or interpreter."},
"Cap. 12":{it:"Niente video sul tuo schermo. La classe, sul proiettore, puo vedere il trailer di The September Issue (R.J. Cutler) sul numero di settembre 2007 di Vogue US. Tu spieghi: Wintour decide cosa entra; Coddington costruisce il racconto per immagini. Il settembre americano e un istituzione, non un catalogo. Domanda: chi in quella stanza puo dire no.",en:"No video on your screen. The class may watch the September Issue trailer. Wintour cuts. Coddington builds the image. Who can say no."},
"Cap. 13":{it:"Niente video qui. La classe vede Enninful Meets Rihanna, Vogue 2018. Tu spieghi: siamo in Vogue House. E un brief di copertina con Nick Knight: sopracciglio, designer, tono. Non e gossip. E la stanza dell editor. Chiedi tre parole del brief.",en:"No video here. Class sees Enninful and Rihanna. A cover brief, not gossip. Three words of the brief."},
"Cap. 14":{it:"Niente video qui. La classe puo vedere 40 Vogue Icons Remember Edward Enninful, venti minuti, marzo 2024. Quaranta cover con Meisel. Tu spieghi: stare in copertina e gia una decisione istituzionale. Chi entra, chi resta fuori.",en:"No video here. Class may watch 40 Vogue Icons. Being on the cover is already an institutional decision."},
"Cap. 15":{it:"Niente video qui. Sulla classe: Prada FW22 ufficiale e Welcome to Milan della Camera Moda. Tu spieghi: lo show e il rito della maison; il film della Camera vende citta e calendario. Due istituzioni. Compito a casa: una copertina, otto righe, un autore.",en:"No video here. Prada is the house ritual. Camera Moda is the city calendar. Two institutions. Homework: one cover, eight lines."},
"Cap. 16":{it:"Copertine Vogue di pubblico dominio. Nome, posa, tipo, credito, stagione, tesi.",en:"Public-domain covers. Six questions."},
"Cap. 17":{it:"Vogue verdetto. i-D scena. Scegline una.",en:"Vogue verdict. i-D scene."},
"Cap. 18":{it:"Coddington racconta. Enninful allarga il casting. Nessuno disegna.",en:"Coddington tells. Enninful widens. Neither designs."},
"Cap. 19":{it:"Due fonti. Cinque righe da soli. Quale istituzione ha reso quel capo moda.",en:"Two sources. Five lines. Which institution."},
"Cap. T":{it:"Testo intero della lezione. Sui video leggi Cap. 12-15, non farli partire da qui.",en:"Full text. On video chapters, read 12-15. Do not play them here."}
};
