window.TEACHER_NOTES={
"Cap. 0":{it:"Non cataloghiamo vestiti. Un oggetto tessile diventa moda solo quando il sistema lo nomina: rivista, sfilata, buyer, editor.",en:"We do not catalogue clothes. A textile object becomes fashion only when the system names it."},
"Cap. 1":{it:"Tu 60 secondi. Loro: nome, citta, perche styling, una rivista. 45 secondi in inglese.",en:"You 60 seconds. Them: name, city, why styling, one magazine."},
"Cap. 2":{it:"Tre assi: ruolo, ricerca, composizione. Autori: Barthes, Mower, Kawamura.",en:"Three axes: role, research, composition. Barthes, Mower, Kawamura."},
"Cap. 3":{it:"Barthes 1967. Capo reale, capo-immagine, capo scritto. Non e l oggetto, e il nome.",en:"Barthes 1967. Real, image, written. It is not the object. It is the name."},
"Cap. 4":{it:"Kawamura. Clothing materiale. Fashion credenza. Senza istituzioni un capo resta un capo.",en:"Kawamura. Clothing is material. Fashion is belief."},
"Cap. 5":{it:"Sei fasi. Lo stylist e forte in comunicazione. Deve leggere la produzione.",en:"Six stages. Strongest in communication. Must still read production."},
"Cap. 6":{it:"Mower: interpreter, not designer. Editor, fotografo, buyer, CD, PR.",en:"Mower: interpreter, not designer."},
"Cap. 7":{it:"Editorial, advertising, celebrity, e-commerce, runway.",en:"Editorial, advertising, celebrity, e-commerce, runway."},
"Cap. 8":{it:"Cinque domande. Chi. Rivista. Stagione. Tesi. Credito.",en:"Five questions. Who. Magazine. Season. Thesis. Credit."},
"Cap. 9":{it:"Fad non e trend. Origine, filtro, cassa.",en:"A fad is not a trend. Origin, filter, till."},
"Cap. 10":{it:"NY Londra Milano Parigi. Lo show costruisce mito.",en:"NY London Milan Paris. The show builds myth."},
"Cap. 11":{it:"Vittima copia. Interprete sceglie.",en:"A victim copies. An interpreter chooses."},
"Cap. 12":{it:"Trailer September Issue. Chi decide, chi interpreta.",en:"September Issue trailer. Who decides, who interprets."},
"Cap. 13":{it:"Vogue ufficiale. Enninful e Rihanna. Il brief.",en:"Official Vogue. Enninful and Rihanna. The brief."},
"Cap. 14":{it:"Film Vogue 20 minuti. Chi sta in copertina e gia una decisione.",en:"Vogue film 20 minutes. The cover is already a decision."},
"Cap. 15":{it:"Prada e Camera Moda. Compito a casa: una copertina, otto righe.",en:"Prada and Camera Moda. Homework: one cover, eight lines."},
"Cap. 16":{it:"Copertine PD. Nome, posa, tipo, credito, stagione, tesi.",en:"PD covers. Name, pose, type, credit, season, thesis."},
"Cap. 17":{it:"Vogue verdetto. i-D scena.",en:"Vogue verdict. i-D scene."},
"Cap. 18":{it:"Coddington racconta. Enninful allarga. Nessuno disegna.",en:"Coddington tells. Enninful widens. Neither designs."},
"Cap. 19":{it:"Due fonti. Cinque righe da soli.",en:"Two sources. Five lines, alone."},
"Cap. T":{it:"Qui c e tutto il testo della lezione.",en:"All lesson text is in this section."}
};
