window.TEACHER_NOTES={
"Cap. 0":{it:"Oggi non cataloghiamo vestiti. Un oggetto diventa moda quando il sistema lo nomina. Non leggere la slide: guarda la classe.",en:"Today we do not catalogue clothes. A garment becomes fashion when the system names it. Do not read the slide. Look at the class."},
"Cap. 1":{it:"Tu 60 secondi. Loro 45 in inglese. Annota la rivista. Niente gruppi.",en:"You: 60 seconds. Them: 45 seconds in English. Note their magazine. No group work."},
"Cap. 2":{it:"Tre obiettivi: ruolo, ricerca, composizione. Cita Barthes, Mower, Kawamura.",en:"Three aims: role, research, composition. Cite Barthes, Mower, Kawamura."},
"Cap. 3":{it:"Barthes 1967. Reale, immagine, scritto. Non e l'oggetto, e il nome.",en:"Barthes 1967. Real, image, written. It is not the object. It is the name."},
"Cap. 4":{it:"Kawamura: clothing e materiale, fashion e credenza. Senza istituzioni un capo resta un capo.",en:"Kawamura: clothing is material, fashion is belief. Without institutions a garment stays a garment."},
"Cap. 5":{it:"Sei fasi. Lo stylist e forte in comunicazione. Deve saper leggere la produzione.",en:"Six stages. The stylist is strong in communication. They must still read production."},
"Cap. 6":{it:"Mower: interpreter, not designer. Non isolare lo stylist.",en:"Mower: interpreter, not designer. Do not isolate the stylist."},
"Cap. 7":{it:"Cinque aree. Editorial piu liberta, meno budget. Advertising: prodotto leggibile.",en:"Five areas. Editorial: more freedom, less budget. Advertising: the product must be readable."},
"Cap. 8":{it:"Cinque domande sulla copertina. Tu le fai. Loro rispondono dalla sedia.",en:"Five questions on the cover. You ask. They answer from their seats."},
"Cap. 9":{it:"Fad non e trend. Origine, filtro, cassa.",en:"A fad is not a trend. Origin, filter, till."},
"Cap. 10":{it:"NY, Londra, Milano, Parigi. Lo show costruisce mito, non conta i capi.",en:"NY, London, Milan, Paris. The show builds myth. It does not count garments."},
"Cap. 11":{it:"Una immagine. Vittima o interprete. Una risposta e si va avanti.",en:"One image. Victim or interpreter. One answer, then move on."},
"Cap. 12":{it:"Trailer The September Issue. Dopo il video: chi decide, chi interpreta.",en:"September Issue trailer. After the film: who decides, who interprets."},
"Cap. 13":{it:"Video ufficiale Vogue. Enninful e Rihanna. Il brief di copertina.",en:"Official Vogue video. Enninful and Rihanna. The cover brief."},
"Cap. 14":{it:"Film Vogue, 20 minuti. Chi viene nominato in copertina e gia una decisione istituzionale.",en:"Vogue film, 20 minutes. Who is named on the cover is already an institutional decision."},
"Cap. 15":{it:"Prada ufficiale e Camera Moda. Show e calendario. Compito individuale a casa.",en:"Official Prada and Camera Moda. Show and calendar. Individual homework."},
"Cap. 16":{it:"Copertine Vogue di pubblico dominio. Sei domande. Non fare storia del costume.",en:"Public-domain Vogue covers. Six questions. This is not costume history."},
"Cap. 17":{it:"Vogue = verdetto. i-D = scena. Sceglierne una.",en:"Vogue = verdict. i-D = scene. Choose one."},
"Cap. 18":{it:"Coddington racconta. Enninful allarga il casting. Nessuno disegna la collezione.",en:"Coddington tells a story. Enninful widens the casting. Neither designs the collection."},
"Cap. 19":{it:"Mostri le copertine. Tu leggi le domande. Niente laboratorio a coppie.",en:"Show the covers. You read the questions. No pair lab."}
};
