window.P0=function(hero,refs,IMG){return [
{k:"Cap. 0",it:"Il Sistema Moda",en:"The Fashion System",talk:"We study the network that turns a garment into fashion.",
html:hero(IMG.milano)+'<div class="pad"><p class="it">Oggi non cataloghiamo vestiti. Studiamo come un oggetto tessile diventa moda: chi lo inventa, chi lo produce, chi lo compra per lo store, chi lo fotografa, chi lo scrive su una rivista, chi lo indossa. La lezione dura 90 minuti: prima la teoria (Barthes e Kawamura), poi il workshop, il pitch in inglese e un test di 8 domande.</p><p class="en">Today we do not catalogue clothes. We study how a textile object becomes fashion: who invents it, who produces it, who buys it for the store, who photographs it, who writes it in a magazine, who wears it. Ninety minutes: theory first (Barthes and Kawamura), then workshop, English pitch, eight-question test.</p><p class="cap">Foto: Milano Fashion Week — Wikimedia Commons, br1dotcom, CC BY-SA.</p>'+refs([IMG.run,IMG.edit,IMG.street])+'<p class="it mu">0–8 presentazioni · 8–30 teoria · 30–68 workshop · 68–83 pitch · 83–90 quiz.</p><p class="en mu">0–8 intro · 8–30 theory · 30–68 workshop · 68–83 pitch · 83–90 quiz.</p></div>'},
{k:"Cap. 1",it:"Presentazioni",en:"Introductions",talk:"Name, city, why styling, one magazine.",
html:hero(IMG.look)+'<div class="pad"><p class="it">Professore: 60 secondi. Ogni studente: 45 secondi in inglese. Niente monologhi. Annoto magazine e riferimenti: serviranno per i gruppi del workshop.</p><p class="en">Professor: 60 seconds. Each student: 45 seconds in English. No monologues. I note magazines and references: they will feed the workshop groups.</p><ul class="x"><li class="it">Nome, città, perché styling e non design o marketing</li><li class="en">Name, city, why styling not design or marketing</li><li class="it">Rivista: Vogue, i-D, Dazed, Purple, Another, Self Service, Document, Interview</li><li class="en">Magazine: Vogue, i-D, Dazed, Purple, Another, Self Service, Document, Interview</li><li class="it">Stylist o editor: Coddington, Enninful, Law Roach</li><li class="en">Stylist or editor: Coddington, Enninful, Law Roach</li></ul></div>'},
{k:"Cap. 2",it:"Obiettivi e letture",en:"Outcomes and readings",talk:"Define the stylist inside the system.",
html:hero(IMG.mag)+'<div class="pad"><p class="it">L01 ruolo dello stylist. L02 ricerca visiva. L03 selezione, proporzioni, colore. Esame: booklet THE COVER MAGAZINE; still life 5+5+5; tre monografie. PDF + orale.</p><p class="en">L01 stylist role. L02 visual research. L03 composition. Exam: three PDF booklets + oral.</p><div class="card"><p class="it"><b>Letture.</b> Barthes, The Fashion System. Mower, Stylist: The Interpreters of Fashion. Kawamura, Fashion-ology. Una copertina Vogue + un editoriale i-D o Purple.</p><p class="en"><b>Readings.</b> Barthes. Mower. Kawamura. One Vogue cover + one i-D or Purple editorial.</p></div></div>'},
{k:"Cap. 3",it:"Barthes: tre indumenti",en:"Barthes: three garments",talk:"Barthes studies magazines. Real, image, written.",
html:hero(IMG.edit)+'<div class="pad"><p class="it">Nel 1967 Roland Barthes analizza Elle e Le Jardin des Modes. Non studia la fabbrica. Studia come la rivista trasforma il vestito in significato. Tesi: non è l’oggetto a creare il desiderio, è il nome. La rivista vela il capo con immagini, ragioni, significati. I tre livelli — indumento reale, indumento-immagine, indumento scritto — restano lo strumento per leggere una copertina.</p><p class="en">In 1967 Roland Barthes analyses Elle and Le Jardin des Modes. He does not study the factory. He studies how the magazine turns dress into meaning. Thesis: it is not the object that creates desire, it is the name. The three levels — real garment, image-garment, written garment — remain the tool for reading a cover.</p><div class="quote">It is not the object but the name that creates desire; it is not the dream but the meaning that sells.<span class="cite">Roland Barthes, The Fashion System</span></div><div class="grid"><div class="card"><h4 class="it">Reale</h4><h4 class="en">Real</h4><p class="it">Taglio, tessuto, atelier.</p><p class="en">Cut, cloth, atelier.</p></div><div class="card"><h4 class="it">Immagine</h4><h4 class="en">Image</h4><p class="it">Foto. Qui lavora lo stylist.</p><p class="en">Photo. Stylist works here.</p></div><div class="card"><h4 class="it">Scritto</h4><h4 class="en">Written</h4><p class="it">Didascalia e credit.</p><p class="en">Caption and credits.</p></div></div><details><summary>Approfondimento</summary><div class="in"><p class="it">Barthes distingue enunciati A (riferimento al mondo) e B (è di moda / non è di moda). I social hanno sostituito parte della didascalia, ma i tre livelli restano lo strumento per leggere una copertina.</p><p class="en">Set A vs set B statements. The three levels still read a cover.</p><p class="cap">Fonte: Barthes, The Fashion System, University of California Press.</p></div></details></div>'}
];};
