window.P2=function(hero,refs,IMG){return [
{k:"Cap. 8",it:"Come si legge una rivista",en:"How to read a magazine",talk:"Read cover, credits, caption, clothes.",
html:hero(IMG.mag)+'<div class="pad"><p class="it">Quattro minuti a coppie. Cinque domande su una copertina.</p><p class="en">Four minutes. Five questions on one cover.</p><ul class="x"><li class="it">1. Chi è in copertina e perché ora?</li><li class="en">1. Who is on the cover and why now?</li><li class="it">2. Quale capo è soggetto, quale atmosfera?</li><li class="en">2. Subject vs atmosphere</li><li class="it">3. Didascalia e credit?</li><li class="en">3. Caption and credits?</li><li class="it">4. Che rivista è? Vogue IT ≠ i-D ≠ Purple</li><li class="en">4. Which magazine?</li><li class="it">5. Dove sta lo stylist?</li><li class="en">5. Where is the stylist?</li></ul><details><summary>Approfondimento · mappa riviste</summary><div class="in"><p class="it">Vogue = autorità e mercato. Vogue Business / BoF = industria. i-D / Dazed = cultura giovane. Purple / Self Service = autore. Another / Document / Interview = arte e ritratto.</p><p class="en">Vogue = authority. Vogue Business / BoF = industry. i-D / Dazed = youth. Purple / Self Service = auteur.</p></div></details></div>'},
{k:"Cap. 9",it:"Trend",en:"Trends",talk:"Origin, filter, amplifier.",
html:hero(IMG.street)+'<div class="pad"><p class="it">Errore da first year: confondere fad (un ciclo social) e trend (durata, origine, diffusione). Il runway non inventa tutto. Spesso certifica ciò che è già in strada, in un archivio o in un tessuto nuovo. Trickle-down, trickle-up e trickle-across oggi convivono.</p><p class="en">First-year error: mixing fad (one social cycle) and trend (duration, origin, spread). The runway does not invent everything. It often certifies what is already in the street, an archive or a new textile. Trickle-down, trickle-up and trickle-across now coexist.</p><ul class="x"><li class="it">Origine — strada, subculture, cinema, sport, archivio</li><li class="en">Origin</li><li class="it">Filtro — uffici tendenza, buyer, CD</li><li class="en">Filter</li><li class="it">Cassa — sfilate, magazine, TikTok, retail</li><li class="en">Amplifier</li></ul></div>'},
{k:"Cap. 10",it:"Fashion Week",en:"Fashion Week",talk:"New York, London, Milan, Paris.",
html:hero(IMG.milano2)+'<div class="pad"><p class="it">L’ordine è sempre New York, Londra, Milano, Parigi. Febbraio mostra l’autunno successivo. Settembre mostra la primavera successiva. Il calendario sincronizza press e buyer. Milano PE27 (settembre 2026): 203 appuntamenti, Prada apre il 22, Armani chiude il 27. Lo show non conta i capi: costruisce mito, autorità, desiderio.</p><p class="en">The order is always New York, London, Milan, Paris. February shows the following autumn. September shows the following spring. The calendar syncs press and buyers. Milan SS27 (September 2026): 203 appointments, Prada opens on the 22nd, Armani closes on the 27th. The show does not count garments: it builds myth, authority, desire.</p>'+refs([IMG.milano,IMG.run,IMG.armani])+'<p class="cap">Foto: Milano Fashion Week — Wikimedia Commons.</p><div class="grid"><div class="card"><h4>NY</h4><p>CFDA · mercato</p></div><div class="card"><h4>London</h4><p>BFC · scuola</p></div><div class="card"><h4>Milano</h4><p>Camera Nazionale · industria</p></div><div class="card"><h4>Parigi</h4><p>Fédération · autorialità</p></div></div><details><summary>Approfondimento · fonti vive</summary><div class="in"><p class="it">Vogue Runway, Vogue Business Fashion Month, calendario Camera Nazionale della Moda Italiana.</p><p class="en">Vogue Runway, Vogue Business, Camera Moda calendar.</p></div></details></div>'},
{k:"Cap. 11",it:"Victim / interprete",en:"Victim / interpreter",talk:"A victim copies. The stylist interprets.",
html:hero(IMG.street)+'<div class="pad"><p class="it">Tre minuti a coppie. Mostrate un’immagine da Instagram o Vogue Runway. Una frase sola: vittima o interprete, e perché. Vittima: look 1:1, logo, paura di restare fuori, nessuna biografia. Interprete: prende colore, volume o riferimento e lo piega a un progetto.</p><p class="en">Three minutes in pairs. Show one image from Instagram or Vogue Runway. One sentence only: victim or interpreter, and why. Victim: look 1:1, logo, fear of being left out, no biography. Interpreter: takes colour, volume or reference and bends it to a project.</p><div class="quote">The stylist does not design the garment. They decide how the garment speaks.<span class="cite">Sarah Mower</span></div></div>'}
];};
