window.P3=function(hero,refs,IMG){return [
{k:"Cap. 12",it:"Video · The September Issue",en:"Video · The September Issue",talk:"Watch how a Vogue issue is made.",
html:'<div class="pad"><p class="it">Documentario di R.J. Cutler sul numero di settembre 2007 di Vogue US. Si vede il sistema: editor, stylist, fotografo, sfilata, taglio finale.</p><p class="en">Cutler film on the 2007 US Vogue September issue.</p><div class="vid"><iframe src="https://www.youtube.com/embed/xp8iIyKDOtk" title="The September Issue trailer" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div><p class="cap">Trailer ufficiale. RoadsideFlix / A and E IndieFilms.</p></div>'},
{k:"Cap. 13",it:"Video · Enninful e British Vogue",en:"Video · Enninful and British Vogue",talk:"Enninful in Vogue House with Rihanna.",
html:'<div class="pad"><p class="it">Canale ufficiale Vogue. Enninful parla con Rihanna del servizio di copertina con Nick Knight.</p><p class="en">Official Vogue channel. Enninful and Rihanna on the Nick Knight cover.</p><div class="vid"><iframe src="https://www.youtube.com/embed/ITsIEPdo4Ik" title="Enninful Meets Rihanna" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div><p class="cap">British Vogue / Vogue YouTube, 2018.</p></div>'},
{k:"Cap. 14",it:"Video · 40 cover Enninful",en:"Video · 40 Enninful covers",talk:"Forty cover stars. An institution naming people.",
html:'<div class="pad"><p class="it">Film ufficiale Vogue sul numero di chiusura di Enninful, marzo 2024. Quaranta cover. Chi sta in copertina è già una decisione istituzionale.</p><p class="en">Official Vogue film, March 2024.</p><div class="vid"><iframe src="https://www.youtube.com/embed/YrpI_Tz9K0I" title="40 Vogue Icons Enninful" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div><p class="cap">Vogue YouTube, 2024. Circa 20 minuti.</p></div>'},
{k:"Cap. 15",it:"Video · Prada e Milano",en:"Video · Prada and Milan",talk:"Watch Prada, then Camera Moda.",
html:'<div class="pad"><p class="it">Prada FW22 ufficiale e Welcome to Milan della Camera Nazionale della Moda Italiana.</p><p class="en">Official Prada FW22 and Camera Moda Welcome to Milan.</p><div class="vid"><iframe src="https://www.youtube.com/embed/ksvXnpnmYOc" title="Prada FW22" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div><p class="cap">Prada YouTube.</p><div class="vid"><iframe src="https://www.youtube.com/embed/4-UWiIcRFZo" title="Welcome to Milan" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div><p class="cap">Camera Nazionale della Moda Italiana, MFW FW19.</p></div>'}
];};
