window.P3=function(hero,refs,IMG){return [
{k:"Cap. 12",it:"Workshop",en:"Workshop",talk:"Four groups. Twenty five minutes.",
html:hero(IMG.mood)+'<div class="pad"><p class="it">Fonti ammesse: Vogue Runway, Vogue Business, sito della maison, i-D, Purple, Camera Moda. Ogni gruppo consegna 3 immagini, 5 righe scritte, una frase finale sullo stylist. Pitch in inglese.</p><p class="en">Allowed sources: Vogue Runway, Vogue Business, house site, i-D, Purple, Camera Moda. Each group delivers 3 images, 5 written lines, one final sentence on the stylist. Pitch in English.</p><p><button id="t25" type="button">Timer 25</button> <button id="t3" type="button">Timer 3</button> <button id="tstop" type="button">Stop</button></p><div class="grid"><div class="card"><h4>G1</h4><p class="it">Un capo, tutta la filiera</p><p class="en">One garment, whole chain</p></div><div class="card"><h4>G2</h4><p class="it">Tre ruoli + una rivista</p><p class="en">Three roles + magazine</p></div><div class="card"><h4>G3</h4><p class="it">Città, tre show, un trend</p><p class="en">City, three shows, one trend</p></div><div class="card"><h4>G4</h4><p class="it">Vibe + due moodboard</p><p class="en">Vibe + two moodboards</p></div></div></div>'},
{k:"Cap. 13",it:"Pitch",en:"Pitch",talk:"Three minutes. In this system the stylist exists to.",
html:hero(IMG.edit)+'<div class="pad"><ul class="x"><li class="it">Tesi chiara</li><li class="en">Clear thesis</li><li class="it">Più di un attore</li><li class="en">More than one actor</li><li class="it">Immagini che argomentano</li><li class="en">Images that argue</li><li class="it">Una fonte nominata</li><li class="en">One named source</li></ul></div>'},
{k:"Cap. 14",it:"Test",en:"Test",talk:"Eight questions.",
html:'<div class="pad"><form class="quiz" id="quiz"><p><b>1</b> Stylist</p><label><input type="radio" name="q1" value="0"> <span class="it">Disegna la collezione</span><span class="en">Designs</span></label><label><input type="radio" name="q1" value="1"> <span class="it">Interpreta un brief</span><span class="en">Interprets a brief</span></label><p><b>2</b> Big 4</p><label><input type="radio" name="q2" value="1"> NY London Milan Paris</label><label><input type="radio" name="q2" value="0"> Paris Milan London NY</label><p><b>3</b> Barthes</p><label><input type="radio" name="q3" value="1"> <span class="it">Reale / immagine / scritto</span><span class="en">Real / image / written</span></label><label><input type="radio" name="q3" value="0"> Brand list</label><p><b>4</b> Kawamura</p><label><input type="radio" name="q4" value="1"> <span class="it">Istituzioni e credenza</span><span class="en">Institutions and belief</span></label><label><input type="radio" name="q4" value="0"> <span class="it">Solo gusto</span><span class="en">Taste only</span></label><p><b>5</b> Cover</p><label><input type="radio" name="q5" value="1"> Vibe + moodboard</label><label><input type="radio" name="q5" value="0"> Business plan</label><p><b>6</b> Victim</p><label><input type="radio" name="q6" value="1"> <span class="it">Trend senza filtro</span><span class="en">No filter</span></label><label><input type="radio" name="q6" value="0"> CD</label><p><b>7</b> Fase</p><label><input type="radio" name="q7" value="1"> <span class="it">Comunicazione visiva</span><span class="en">Visual communication</span></label><label><input type="radio" name="q7" value="0"> Factory</label><p><b>8</b> Show</p><label><input type="radio" name="q8" value="1"> <span class="it">Mito, autorità, desiderio</span><span class="en">Myth, authority, desire</span></label><label><input type="radio" name="q8" value="0"> Count</label><p style="margin-top:12px"><button type="submit">Invia</button></p></form><div class="result" id="result"></div></div>'},
{k:"Cap. 15",it:"Compito",en:"Homework",talk:"Choose one magazine. Read Barthes, Mower, Kawamura.",
html:hero(IMG.mag)+'<div class="pad"><ul class="x"><li class="it">Magazine + 8 righe di vibe</li><li class="en">Magazine + 8 lines of vibe</li><li class="it">10 immagini</li><li class="en">10 images</li><li class="it">Barthes + Mower + Kawamura 3–4 + copertina con 5 domande</li><li class="en">Barthes + Mower + Kawamura 3–4 + one cover</li></ul><p class="it mu">Barthes; Mower; Kawamura; Vogue Runway; Vogue Business; Camera Moda; Another, Dazed, Document, i-D, Interview, Purple, Self Service, Vogue.</p><p class="en mu">Same bibliography.</p></div>'}
];};
