window.P3=function(hero,refs,IMG){return [
{k:"Cap. 12",it:"Workshop",en:"Workshop",talk:"Four groups. Thirty minutes. Written first. Pitch after.",
html:hero(IMG.mood)+'<div class="pad"><p class="it">Niente quiz. Ogni gruppo scrive PRIMA: 3 immagini, 5 righe, una frase sullo stylist. Poi pitch di 2 minuti. Correzione con schede inglesi già scritte.</p><p class="en">No quiz. Write first, then a 2-minute pitch. Correction uses ready English cards.</p><p><button id="t25" type="button">Timer 30</button> <button id="t3" type="button">Timer 2</button> <button id="tstop" type="button">Stop</button></p><div class="grid"><div class="card"><h4>G1</h4><p class="it">Un capo, tutta la filiera</p><p class="en">One garment, whole chain</p></div><div class="card"><h4>G2</h4><p class="it">Tre ruoli + una rivista</p><p class="en">Three roles + magazine</p></div><div class="card"><h4>G3</h4><p class="it">Città, tre show, un trend</p><p class="en">City, three shows, one trend</p></div><div class="card"><h4>G4</h4><p class="it">Vibe + due moodboard</p><p class="en">Vibe + two moodboards</p></div></div></div>'},
{k:"Cap. 13",it:"Pitch",en:"Pitch",talk:"Two minutes. I listen. Then I use the correction cards.",
html:hero(IMG.edit)+'<div class="pad"><p class="it">Ordine G1–G4. Due minuti. Non interrompere. Annota quattro punti. Poi schede.</p><p class="en">Order G1–G4. Two minutes. Do not interrupt.</p><ul class="x"><li class="it">Tesi?</li><li class="en">Thesis?</li><li class="it">Più attori?</li><li class="en">More actors?</li><li class="it">Immagini?</li><li class="en">Images?</li><li class="it">Fonte?</li><li class="en">Source?</li></ul></div>'},
{k:"Cap. 14",it:"Correzione gruppi",en:"Group correction",talk:"I speak Italian. The card speaks English. You do not need to improvise.",
html:hero(IMG.look)+'<div class="pad"><p class="it"><b>Tu parli italiano.</b> Poi premi Voce EN. La macchina legge la correzione. Tu resti padrone del contenuto.</p><p class="en">You speak Italian. Then press Voice. The machine reads English.</p><p><button type="button" class="say" data-say="Thank you. I will give the correction in English, then we stay on the content.">Aprire · Voce EN</button></p><details open><summary>Schede pronte</summary><div class="in"><p class="it">Manca istituzione</p><p><button type="button" class="say" data-say="You showed clothes. You did not show the institution that makes them count as fashion. Name the magazine, the buyer or the show.">Voce EN</button></p><p class="it">Manca Barthes</p><p><button type="button" class="say" data-say="Tell me which part is the real garment, which part is the image, and which part is the written caption.">Voce EN</button></p><p class="it">Solo victim</p><p><button type="button" class="say" data-say="This is a copy of a look. A stylist interprets. Take one colour or one volume and bend it to a project.">Voce EN</button></p><p class="it">Nessuna fonte</p><p><button type="button" class="say" data-say="Name one source: Vogue Runway, Vogue Business, i-D, Purple or the official calendar.">Voce EN</button></p><p class="it">Bene, alzare</p><p><button type="button" class="say" data-say="Good. Now one sharper sentence: the garment is material; fashion is the belief produced around that garment.">Voce EN</button></p><p class="it">Chiudere</p><p><button type="button" class="say" data-say="Rewrite five lines for next week. Keep the images. Change the sentence on the stylist.">Voce EN</button></p></div></details></div>'},
{k:"Cap. 15",it:"Compito",en:"Homework",talk:"Rewrite the five lines after correction.",
html:hero(IMG.mag)+'<div class="pad"><p class="it">Stesse 3 immagini, 5 righe nuove, una frase nuova sullo stylist.</p><p class="en">Same 3 images, five new lines, one new sentence on the stylist.</p></div>'}
];};
