window.P4=function(hero,refs,IMG){return [
{k:"Cap. 16",it:"Anatomia di una copertina Vogue",en:"Anatomy of a Vogue cover",talk:"A cover is written garment plus image-garment. Read name, pose, type, credit.",
html:hero(IMG.v1922)+'<div class="pad"><p class="it">Queste sono copertine Vogue di pubblico dominio (1916–1930). Servono come laboratorio, non come nostalgia. Barthes si allena qui: il nome «Vogue» già vende prima del vestito. La posa, il titolo, il disegno sono l’indumento-immagine. Se ci fosse una didascalia («abito da sera in crêpe»), sarebbe l’indumento scritto.</p><p class="en">These are public-domain Vogue covers (1916–1930). They are a lab, not nostalgia. Barthes trains here: the name Vogue already sells before the dress. Pose, title and drawing are the image-garment. A caption would be the written garment.</p>'+refs([IMG.v1916,IMG.v1926,IMG.v1930])+'<p class="cap">Fonti: Wikimedia Commons, Category:Vogue covers. Copertine USA ante 1931, pubblico dominio.</p><details open><summary>Approfondimento · come si legge in 6 minuti</summary><div class="in"><p class="it">1. Chi è il soggetto? 2. Che capo si capisce davvero? 3. Che mondo promette? 4. Disegno o foto? 5. Dove starebbe oggi il credit dello stylist? 6. Perché è Vogue e non un catalogo?</p><p class="en">1. Who is the subject? 2. Which garment is readable? 3. What world is promised? 4. Drawing or photo? 5. Where would the stylist credit sit? 6. Why Vogue not a catalogue?</p></div></details></div>'},
{k:"Cap. 17",it:"Da Vogue autorità a i-D cultura",en:"From Vogue authority to i-D culture",talk:"Same system, different certifiers. Vogue legitimates. i-D documents a scene.",
html:hero(IMG.moss)+'<div class="pad"><p class="it">Vogue costruisce autorità e mercato: copertina = verdetto. i-D, nata nel 1980 da Terry Jones, parte dalla strada e dallo wink. Purple e Self Service puntano sull’autore. Dazed mescola musica e moda giovane. Kawamura: cambia il gatekeeper, non sparisce il sistema. Per il booklet scegliete UNA sola istituzione.</p><p class="en">Vogue builds authority and market. i-D (1980, Terry Jones) documents a scene before luxury certifies it. The gatekeeper changes, the system does not vanish. Choose ONE institution for the booklet.</p>'+refs([IMG.moss,IMG.id1980,IMG.edit])+'<p class="cap">Kate Moss, British Vogue maggio 2000. Primo i-D 1980. Wikimedia Commons.</p></div>'},
{k:"Cap. 18",it:"Caso Coddington / Enninful",en:"Case: Coddington / Enninful",talk:"Two editors, two ways to make a garment count as fashion inside Vogue.",
html:hero(IMG.edit)+'<div class="pad"><p class="it">Grace Coddington costruisce racconti: il capo entra in una fiaba o in un set. Edward Enninful allarga chi può stare in copertina e tiene insieme street e couture. Nessuno dei due disegna la collezione. Entrambi decidono quale immagine diventa canone.</p><p class="en">Coddington builds stories. Enninful widens who can be on the cover. Neither designs the collection. Both decide which image becomes canon.</p><details open><summary>Esercizio 8 minuti</summary><div class="in"><p class="it">Aprite una copertina viva. Una riga: più Coddington o più Enninful? Una riga Barthes: dove sta l’indumento reale?</p><p class="en">Open a live cover. One line: more Coddington or more Enninful? One Barthes line: where is the real garment?</p></div></details></div>'},
{k:"Cap. 19",it:"Laboratorio 20 minuti",en:"Lab 20 minutes",talk:"Pairs. One historic cover and one live cover. Write five lines.",
html:hero(IMG.v1916)+'<div class="pad"><p class="it">A coppie. 20 minuti. Scritto. Fonte A: copertina Vogue 1916–1930. Fonte B: copertina viva. Cinque righe: istituzioni, reale, immagine, scritto, stylist.</p><p class="en">Pairs. 20 minutes. Written. Source A historic Vogue. Source B live cover. Five lines.</p><p><button id="t20" type="button">Timer 20</button></p></div>'}
];};
